export interface Project {
  slug: string;
  title: string;
  category: string;
  tags: string[];
  imageSrc: string;
  videoSrc: string;
  client: string;
  year: string;
  role: string;
  story: string;
  challenge: string;
  solution: string;
  credits: { role: string; name: string }[];
  testimonial: {
    name: string;
    role: string;
    company?: string;
    quote: string;
    thumbnailUrl: string;
    videoUrl?: string;
  };
  gallery: string[];
}

export const projectsData: Project[] = [
  {
    slug: "indo-korean",
    title: "Indo Korean",
    category: "Corporate",
    tags: ["Documentary", "Culture", "Cinematic"],
    imageSrc: "/images/indo korean/011.webp",
    videoSrc: "/videos/indo korean/Indo Korean.mp4",
    client: "Indo-Korean Cultural Society",
    year: "2025",
    role: "Full Production & Direction",
    story: "Exploring the rich cultural intersections between India and Korea, this documentary weaves together personal narratives, culinary traditions, and visual artistry into a seamless, cinematic journey.",
    challenge: "Bridging the cultural dialogue and documenting historical linkages in high-contrast cinematic styles under natural outdoor lighting conditions.",
    solution: "Utilized dual camera rigs and custom anamorphic lenses, capturing authentic cross-cultural exchanges and color grading the warm aesthetic.",
    credits: [
      { role: "Director / DP", name: "Praise" },
    ],
    testimonial: {
      name: "Marcus Vance",
      role: "Creative Director",
      company: "Vanguard Studios",
      quote: "The visual depth and emotional core of Indo Korean exceeded our expectations. Havilah is a class apart.",
      thumbnailUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=800",
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    gallery: [
      "/images/indo korean/001.webp",
      "/images/indo korean/002.webp",
      "/images/indo korean/003.webp",
      "/images/indo korean/004.webp",
      "/images/indo korean/005.webp",
      "/images/indo korean/006.webp",
      "/images/indo korean/007.webp",
      "/images/indo korean/008.webp",
      "/images/indo korean/009.webp",
      "/images/indo korean/010.webp",
      "/images/indo korean/011.webp",
      "/images/indo korean/012.webp",
      "/images/indo korean/013.webp",
      "/images/indo korean/014.webp",
      "/images/indo korean/015.webp",
      "/images/indo korean/016.webp",
      "/images/indo korean/017.webp"
    ],
  },
  {
    slug: "real-estate",
    title: "Real Estate",
    category: "Commercials",
    tags: ["Commercial", "Architecture", "Luxury"],
    imageSrc: "/images/real estate/image.avif",
    videoSrc: "/videos/reaal estate/4Bhk Whitefield Near Metro Station.mp4",
    client: "Whitefield Developments",
    year: "2026",
    role: "Drone Aerials & Interior Shifting",
    story: "A premium showcase of modern architectural marvels. We focused on capturing the scale, light, and luxury of these properties using sweeping drone shots and intimate interior details.",
    challenge: "Executing steady interior camera movements in tight, complex architectural layout structures while maintaining high lighting fidelity.",
    solution: "Deployed lightweight, heavy-lift drone stabilizers and shot using wide-angle primes with high exposure latitudes.",
    credits: [
      { role: "Director / DP", name: "Praise" },
    ],
    testimonial: {
      name: "Sophia Rossi",
      role: "Lead Producer",
      company: "Aura Films",
      quote: "The commercial spot we launched redefined how our consumer base views our properties. Outstanding results.",
      thumbnailUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=800",
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    gallery: [
      "/images/real estate/image.avif",
      "/videos/reaal estate/Real Estate Video 720P.mp4",
      "/videos/reaal estate/Poulomi Florique.mp4",
      "/videos/reaal estate/Assetz Paradise Mizu & Ski.mp4"
    ],
  },
  {
    slug: "young-indians",
    title: "Young Indians",
    category: "Documentaries",
    tags: ["Documentary", "Portrait", "Gritty"],
    imageSrc: "/images/young-indians/053.webp",
    videoSrc: "/videos/YI/Iy-Reel.mp4",
    client: "Young Indians Youth League",
    year: "2025",
    role: "Directing & Editorial Cuts",
    story: "A gritty, authentic look into the lives of the next generation. We followed subjects across the country to capture their drive, their challenges, and their unbroken spirit.",
    challenge: "Capturing organic, unscripted moments on location in noisy street corridors and working-class quarters.",
    solution: "Used compact mirrorless rigs and natural lighting to maintain a minimal crew footprint, earning the trust of local subjects.",
    credits: [
      { role: "Director / DP", name: "Praise" },
    ],
    testimonial: {
      name: "Jameson Lee",
      role: "Head of Marketing",
      company: "Horizon Auto",
      quote: "A breathtaking piece of ecological journalism. Their commitment under extreme conditions was phenomenal.",
      thumbnailUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=800",
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    gallery: [
      "/images/young-indians/001.webp",
      "/images/young-indians/002.webp",
      "/images/young-indians/003.webp",
      "/images/young-indians/004.webp",
      "/images/young-indians/005.webp",
      "/images/young-indians/006.webp",
      "/images/young-indians/007.webp",
      "/images/young-indians/008.webp",
      "/images/young-indians/009.webp",
      "/images/young-indians/010.webp",
      "/images/young-indians/011.webp",
      "/images/young-indians/012.webp",
      "/images/young-indians/013.webp",
      "/images/young-indians/014.webp",
      "/images/young-indians/015.webp",
      "/images/young-indians/016.webp",
      "/images/young-indians/017.webp",
      "/images/young-indians/018.webp",
      "/images/young-indians/019.webp",
      "/images/young-indians/020.webp",
      "/images/young-indians/021.webp",
      "/images/young-indians/022.webp",
      "/images/young-indians/023.webp",
      "/images/young-indians/024.webp",
      "/images/young-indians/025.webp",
      "/images/young-indians/026.webp",
      "/images/young-indians/027.webp",
      "/images/young-indians/028.webp",
      "/images/young-indians/029.webp",
      "/images/young-indians/030.webp",
      "/images/young-indians/031.webp",
      "/images/young-indians/032.webp",
      "/images/young-indians/033.webp",
      "/images/young-indians/034.webp",
      "/images/young-indians/035.webp",
      "/images/young-indians/036.webp",
      "/images/young-indians/037.webp",
      "/images/young-indians/038.webp",
      "/images/young-indians/039.webp",
      "/images/young-indians/040.webp",
      "/images/young-indians/041.webp",
      "/images/young-indians/042.webp",
      "/images/young-indians/043.webp",
      "/images/young-indians/044.webp",
      "/images/young-indians/045.webp",
      "/images/young-indians/046.webp",
      "/images/young-indians/047.webp",
      "/images/young-indians/048.webp",
      "/images/young-indians/049.webp",
      "/images/young-indians/050.webp",
      "/images/young-indians/051.webp",
      "/images/young-indians/052.webp",
      "/images/young-indians/053.webp",
      "/images/young-indians/054.webp",
      "/images/young-indians/055.webp",
      "/images/young-indians/056.webp",
      "/images/young-indians/057.webp",
      "/images/young-indians/058.webp",
      "/images/young-indians/059.webp",
      "/images/young-indians/060.webp",
      "/images/young-indians/061.webp",
      "/images/young-indians/062.webp"
    ],
  },
  {
    slug: "naveen-sharlien",
    title: "Naveen Sharlien Wedding",
    category: "Narratives",
    tags: ["Wedding", "Love", "Event"],
    imageSrc: "/images/naveen sharlien/Church/012.webp",
    videoSrc: "/videos/naveen sharlien/BIKE VINTAGE.mp4",
    client: "Naveen & Sharlien",
    year: "2026",
    role: "Cinematic Capture & Editing",
    story: "A beautiful celebration of love. We captured the intimate moments, the grand celebrations, and the raw emotions of Naveen and Sharlien’s special day, creating a cinematic wedding film that they will cherish forever.",
    challenge: "Documenting church ceremony segments under low natural light settings without active flashing equipment.",
    solution: "Deployed f/1.2 high-speed prime setups and dual-native ISO camera logs to preserve the natural warmth of the church architecture.",
    credits: [
      { role: "Director / DP", name: "Praise" },
    ],
    testimonial: {
      name: "Elena Rostova",
      role: "Academy Alumna",
      company: "Freelance Director",
      quote: "The wedding film they developed gave our celebration an unmatched visual warmth. Brilliant work.",
      thumbnailUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800",
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    gallery: [
      "/images/naveen sharlien/001.png",
      "/videos/naveen sharlien/NAVEEN SHARLIEN PHOTOSLIDESHOW.mp4",
      "/videos/naveen sharlien/SHARLIEN NAVEEN HALDI.mp4"
    ],
  },
  {
    slug: "srusti-pratik-haldi",
    title: "Srusti Pratik Haldi",
    category: "Narratives",
    tags: ["Wedding", "Haldi", "Vibrant"],
    imageSrc: "/images/srusti pratik/010.webp",
    videoSrc: "/videos/Srusti Pratik/Haldi Pratik Srusti.mp4",
    client: "Srusti & Pratik",
    year: "2025",
    role: "Production Crew & Highlights",
    story: "A vibrant explosion of color, tradition, and pure joy. We documented the beautiful Haldi ceremony of Srusti and Pratik, focusing on the intimate rituals and the beautiful chaos of family celebrations.",
    challenge: "Keeping camera optics clean and dry during high-speed turmeric throwing and splash segments.",
    solution: "Utilized weather-sealed camera packages, rain covers, and long focal zoom lenses to capture macro emotional close-ups from safe distances.",
    credits: [
      { role: "Director / DP", name: "Praise" },
    ],
    testimonial: {
      name: "Marcus Vance",
      role: "Creative Director",
      company: "Vanguard Studios",
      quote: "The ceremony fidelity was unbelievable. It looks like a high-budget feature film production.",
      thumbnailUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=800",
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    gallery: [
      "/images/srusti pratik/001.webp",
      "/images/srusti pratik/002.webp",
      "/images/srusti pratik/003.webp",
      "/images/srusti pratik/004.webp",
      "/images/srusti pratik/005.webp",
      "/images/srusti pratik/006.webp",
      "/images/srusti pratik/007.webp",
      "/images/srusti pratik/008.webp",
      "/images/srusti pratik/009.webp",
      "/images/srusti pratik/010.webp",
      "/images/srusti pratik/011.webp",
      "/images/srusti pratik/012.webp",
      "/images/srusti pratik/013.webp",
      "/images/srusti pratik/015.webp",
      "/images/srusti pratik/016.webp",
      "/images/srusti pratik/017.webp",
      "/images/srusti pratik/018.webp",
      "/images/srusti pratik/019.webp",
      "/images/srusti pratik/020.webp",
      "/images/srusti pratik/021.webp",
      "/images/srusti pratik/022.webp",
      "/images/srusti pratik/023.webp",
      "/images/srusti pratik/024.webp",
      "/images/srusti pratik/025.webp",
      "/images/srusti pratik/026.webp",
      "/images/srusti pratik/027.webp",
      "/images/srusti pratik/028.webp",
      "/images/srusti pratik/029.webp",
      "/images/srusti pratik/030.webp",
      "/images/srusti pratik/031.webp",
      "/images/srusti pratik/032.webp",
      "/images/srusti pratik/033.webp",
      "/images/srusti pratik/034.webp",
      "/images/srusti pratik/035.webp",
      "/images/srusti pratik/036.webp",
      "/images/srusti pratik/037.webp",
      "/images/srusti pratik/038.webp",
      "/images/srusti pratik/039.webp",
      "/images/srusti pratik/040.webp",
      "/images/srusti pratik/041.webp",
      "/images/srusti pratik/042.webp",
      "/images/srusti pratik/043.webp",
      "/images/srusti pratik/044.webp",
      "/images/srusti pratik/045.webp",
      "/images/srusti pratik/046.webp",
      "/images/srusti pratik/047.webp",
      "/images/srusti pratik/048.webp",
      "/images/srusti pratik/049.webp",
      "/images/srusti pratik/050.webp",
      "/images/srusti pratik/051.webp",
      "/images/srusti pratik/052.webp",
      "/images/srusti pratik/053.webp",
      "/images/srusti pratik/054.webp",
      "/images/srusti pratik/055.webp",
      "/images/srusti pratik/056.webp",
      "/images/srusti pratik/057.webp",
      "/images/srusti pratik/058.webp",
      "/images/srusti pratik/059.webp",
      "/images/srusti pratik/060.webp",
      "/images/srusti pratik/061.webp",
      "/images/srusti pratik/062.webp",
      "/images/srusti pratik/063.webp",
      "/images/srusti pratik/064.webp",
      "/images/srusti pratik/065.webp",
      "/images/srusti pratik/066.webp",
      "/images/srusti pratik/067.webp",
      "/images/srusti pratik/banner.webp"
    ],
  },
  {
    slug: "medtourin",
    title: "Medtourin",
    category: "Commercials",
    tags: ["Commercial", "Healthcare", "Corporate"],
    imageSrc: "/images/medtourin/image.avif",
    videoSrc: "/videos/medtourin/001.mp4",
    client: "Medtourin Healthcare",
    year: "2025",
    role: "Full Production & Visuals",
    story: "A compelling showcase of medical innovation and healthcare excellence, outlining high-fidelity surgical robotics and patient care experiences.",
    challenge: "Maintaining strict sterile laboratory conditions while managing camera rigs, stabilizers, and lighting grids.",
    solution: "Coordinated camera team sanitization loops and deployed small-footprint LED tubes for medical lighting highlights.",
    credits: [
      { role: "Director / DP", name: "Praise" },
    ],
    testimonial: {
      name: "Sophia Rossi",
      role: "Lead Producer",
      company: "Aura Films",
      quote: "Breathtaking visual scopes. The details made the medical innovation look highly premium.",
      thumbnailUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=800",
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    gallery: [
      "/images/medtourin/image.avif",
      "/videos/medtourin/002.mp4",
      "/videos/medtourin/003.mp4",
      "/videos/medtourin/004.mp4"
    ],
  },
  {
    slug: "popnosh",
    title: "Popnosh",
    category: "Branding",
    tags: ["Café", "Hospitality", "Promo"],
    imageSrc: "/images/popnosh/image.png",
    videoSrc: "/videos/popnosh/popnosh.mp4",
    client: "Popnosh Hospitality",
    year: "2026",
    role: "Commercial Shoot & Script",
    story: "A feel good café and hospitality showcase, documenting artisanal coffee preparations and warm, welcoming customer spaces.",
    challenge: "Reflecting the organic aroma and warm visual aesthetics of micro-brewing inside high-density modern layouts.",
    solution: "Utilized macro lenses for detailed espresso extraction frames and color graded using warm gold and vintage tones.",
    credits: [
      { role: "Director / DP", name: "Praise" },
    ],
    testimonial: {
      name: "Marcus Vance",
      role: "Creative Director",
      company: "Vanguard Studios",
      quote: "The final commercial was exceptionally high quality. Customers frequently reference the video look.",
      thumbnailUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=800",
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    gallery: [
      "/images/popnosh/image.png"
    ],
  },
];
